= 
:allow-uri-read: 


[role="tabbed-block"]
====
.Asta三端操作员
--
. https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy-operator.html#step-1-download-the-trident-installer-package["下载Asta三端安装程序并解压缩"^]。
. 如果您尚未安装Astra三端安装程序、或者您从初始Astra三端安装程序中删除了操作员、请完成以下步骤：
+
.. 创建客户需求日：
+
[source, console]
----
kubectl create -f deploy/crds/trident.netapp.io_tridentorchestrators_crd_post1.16.yaml
----
.. 创建三项命名空间 (`kubectl create namespace trident`)或确认三项命名空间仍然存在 (`kubectl get all -n trident`）。如果已删除此命名空间、请重新创建它。


. 将Astra Trdent更新到24.02.0：
+

NOTE: 对于运行Kubornetes 1.24或更早版本的集群、请使用 `bundle_pre_1_25.yaml`。对于运行Kubernetes 1.25或更高版本的集群、请使用 `bundle_post_1_25.yaml`。

+
[source, console]
----
kubectl -n trident apply -f trident-installer/deploy/<bundle-name.yaml>
----
. 验证Astra trident是否正在运行：
+
[source, console]
----
kubectl get torc -n trident
----
+
响应：

+
[listing]
----
NAME      AGE
trident   21m
----
. [[pull机密]]如果您有一个使用机密的注册表，请创建一个用于提取Astra Control置备程序映像的密钥：
+
[source, console]
----
kubectl create secret docker-registry <secret_name> -n trident --docker-server=<my_custom_registry> --docker-username=<username> --docker-password=<token>
----
. 编辑TridentOrchestrator CR并进行以下编辑：
+
[source, console]
----
kubectl edit torc trident -n trident
----
+
.. 为Astra三端映像设置自定义注册表位置或从Astra Control注册表中提取该映像 (`tridentImage: <my_custom_registry>/trident:24.02.0` 或 `tridentImage: netapp/trident:24.02.0`）。
.. 启用Asta Control配置程序 (`enableACP: true`）。
.. 设置Asta Control配置程序映像的自定义注册表位置或将其从Asta Control注册表中提取 (`acpImage: <my_custom_registry>/trident-acp:24.02.0` 或 `acpImage: cr.astra.netapp.io/trident-acp:24.02.0`）。
.. 如果您已建立 <<pull-secrets,图像拉取密钥>> 在本操作步骤的前面部分、您可以在此处设置它们 (`imagePullSecrets: - <secret_name>`）。使用您在前面步骤中创建的相同名称机密名称。


+
[listing, subs="+quotes"]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  *tridentImage: <registry>/trident:24.02.0*
  *enableACP: true*
  *acpImage: <registry>/trident-acp:24.02.0*
  *imagePullSecrets:
  - <secret_name>*
----
. 保存并退出文件。部署过程将自动开始。
. 验证是否已创建操作员、部署和副本集。
+
[source, console]
----
kubectl get all -n trident
----
+

IMPORTANT: 在 Kubernetes 集群中只能有 * 一个操作符实例 * 。请勿创建多个部署的Asta三端操作员。

. 验证 `trident-acp` 容器正在运行 `acpVersion` 为 `24.02.0` 状态为 `Installed`：
+
[source, console]
----
kubectl get torc -o yaml
----
+
响应：

+
[listing]
----
status:
  acpVersion: 24.02.0
  currentInstallationParams:
    ...
    acpImage: <registry>/trident-acp:24.02.0
    enableACP: "true"
    ...
  ...
  status: Installed
----


--
.Tridentctl
--
. https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy-tridentctl.html#step-1-download-the-trident-installer-package["下载Asta三端安装程序并解压缩"^]。
. https://docs.netapp.com/us-en/trident/trident-managing-k8s/upgrade-tridentctl.html["如果您已有Asta Trident、请从托管它的集群中将其卸载"^]。
. 在启用Asta Control配置程序的情况下安装Asta Trent (`--enable-acp=true`）：
+
[source, console]
----
./tridentctl -n trident install --enable-acp=true --acp-image=mycustomregistry/trident-acp:24.02
----
. 确认已启用Asta Control配置程序：
+
[source, console]
----
./tridentctl -n trident version
----
+
响应：

+
[listing]
----
+----------------+----------------+-------------+ | SERVER VERSION | CLIENT VERSION | ACP VERSION | +----------------+----------------+-------------+ | 24.02.0 | 24.02.0 | 24.02.0. | +----------------+----------------+-------------+
----


--
.掌舵
--
. 如果您安装了Astra Trident 23.07.1或更早版本、 https://docs.netapp.com/us-en/trident/trident-managing-k8s/uninstall-trident.html#uninstall-a-trident-operator-installation["卸载"^] 操作员和其他组件。
. 如果您的Kubornetes集群运行的是1.24或更早版本、请删除PSP：
+
[listing]
----
kubectl delete psp tridentoperatorpod
----
. 添加Astra Trident Helm存储库：
+
[listing]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
. 更新Helm图表：
+
[listing]
----
helm repo update netapp-trident
----
+
响应：

+
[listing]
----
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "netapp-trident" chart repository
Update Complete. ⎈Happy Helming!⎈
----
. 列出图像：
+
[listing]
----
./tridentctl images -n trident
----
+
响应：

+
[listing]
----
| v1.28.0            | netapp/trident:24.02.0|
|                    | docker.io/netapp/trident-autosupport:24.02|
|                    | registry.k8s.io/sig-storage/csi-provisioner:v4.0.0|
|                    | registry.k8s.io/sig-storage/csi-attacher:v4.5.0|
|                    | registry.k8s.io/sig-storage/csi-resizer:v1.9.3|
|                    | registry.k8s.io/sig-storage/csi-snapshotter:v6.3.3|
|                    | registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.10.0 |
|                    | netapp/trident-operator:24.02.0 (optional)
----
. 确保提供了三项运算符24.02.0：
+
[listing]
----
helm search repo netapp-trident/trident-operator --versions
----
+
响应：

+
[listing]
----
NAME                            CHART VERSION   APP VERSION     DESCRIPTION
netapp-trident/trident-operator 100.2402.0      24.02.0         A
----
. 使用 ... `helm install` 并运行以下选项之一、其中包括这些设置：
+
** 部署位置的名称
** Astra三端版本
** Asta Control配置程序映像的名称
** 用于启用配置程序的标志
** (可选)本地注册表路径。如果您使用的是本地注册表、则为 https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html#container-images-and-corresponding-kubernetes-versions["｛\f270｛\f151｛\f270｝"^] 可以位于一个注册表或不同的注册表中、但所有CSI映像都必须位于同一注册表中。
** 三端名称空间




.选项
* 没有注册表的映像


[listing]
----
helm install trident netapp-trident/trident-operator --version 100.2402.0 --set acpImage=cr.astra.netapp.io/trident-acp:24.02.0 --set enableACP=true --set operatorImage=netapp/trident-operator:24.02.0 --set tridentAutosupportImage=docker.io/netapp/trident-autosupport:24.02 --set tridentImage=netapp/trident:24.02.0 --namespace trident
----
* 一个或多个注册表中的图像


[listing]
----
helm install trident netapp-trident/trident-operator --version 100.2402.0 --set acpImage=<your-registry>:<acp image> --set enableACP=true --set imageRegistry=<your-registry>/sig-storage --set operatorImage=netapp/trident-operator:24.02.0 --set tridentAutosupportImage=docker.io/netapp/trident-autosupport:24.02 --set tridentImage=netapp/trident:24.02.0 --namespace trident
----
您可以使用 `helm list` 查看安装详细信息、例如名称、命名空间、图表、状态、应用程序版本、和修订版号。

[NOTE]
====
如果您在使用Helm部署TRIdent时遇到任何问题、请运行此命令以完全卸载Asta TRIdent：

[listing]
----
./tridentctl uninstall -n trident
----
*请勿* https://docs.netapp.com/us-en/trident/troubleshooting.html#completely-remove-astra-trident-and-crds["完全删除Asta Trdent CRD"^] 在尝试重新启用Astra Control配置程序之前、作为卸载的一部分。

====
--
====