---
sidebar: sidebar 
permalink: use/manage-connections.html 
keywords: manage package, packages, install 
summary: 您可以将软件包上传并安装到Astra控制中心。 
---
= 管理存储库连接
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


您可以将存储库连接到Astra Control、以用作软件包安装映像和项目的参考。导入软件包时、Astra Control会引用映像存储库中的安装映像以及项目存储库中的二进制文件和其他项目。

.您需要什么？ #8217 ；将需要什么
* 安装了 Astra 控制中心的 Kubernetes 集群
* 一个正在运行的Docker存储库、您可以访问该存储库
* 可访问的正在运行的项目存储库(如Artifactory)




== 连接Docker映像存储库

您可以连接Docker映像存储库以保存软件包安装映像、例如用于Astra数据存储的安装映像。安装软件包时、Astra Control会从映像存储库导入软件包映像文件。

.步骤
. 在 * 管理帐户 * 导航区域中，选择 * 帐户 * 。
. 选择*连接*选项卡。
. 在* Docker映像存储库*部分中、选择右上角的菜单。
. 选择 * 连接 * 。
. 添加存储库的URL和端口。
. 输入存储库的凭据。
. 选择 * 连接 * 。


存储库已连接。在* Docker映像存储库*部分中、存储库应显示已连接状态。



== 断开Docker映像存储库的连接

如果不再需要与Docker映像存储库的连接、您可以将其删除。

.步骤
. 在 * 管理帐户 * 导航区域中，选择 * 帐户 * 。
. 选择*连接*选项卡。
. 在* Docker映像存储库*部分中、选择右上角的菜单。
. 选择*断开连接*。
. 选择*是、断开Docker映像存储库*。


存储库已断开连接。在* Docker映像存储库*部分中、存储库应显示已断开连接状态。



== 连接项目存储库

您可以将项目存储库连接到主机项目、例如软件包二进制文件。安装软件包时、Astra Control会从映像存储库导入软件包的项目。

.步骤
. 在 * 管理帐户 * 导航区域中，选择 * 帐户 * 。
. 选择*连接*选项卡。
. 在*项目存储库*部分中、选择右上角的菜单。
. 选择 * 连接 * 。
. 添加存储库的URL和端口。
. 如果需要身份验证、请启用*使用身份验证*复选框并输入存储库的凭据。
. 选择 * 连接 * 。


存储库已连接。在*项目存储库*部分中、存储库应显示已连接状态。



== 断开项目存储库的连接

如果不再需要与项目存储库的连接、您可以将其删除。

.步骤
. 在 * 管理帐户 * 导航区域中，选择 * 帐户 * 。
. 选择*连接*选项卡。
. 在*项目存储库*部分中、选择右上角的菜单。
. 选择*断开连接*。
. 选择*是、断开项目存储库*。


存储库已断开连接。在*项目存储库*部分中、存储库应显示已连接状态。

[discrete]
== 了解更多信息

* link:manage-packages-acc.html["管理软件包"]

