---
sidebar: sidebar 
permalink: use/manage-users.html 
keywords: add users, edit users, remove users, delete users 
summary: 将用户添加到 Astra 控制中心系统，并删除不应再访问该系统的用户。 
---
= 管理用户
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


您可以使用 Astra Control UI 邀请，添加，删除和编辑 Astra Control Center 安装的用户。您可以使用 Astra Control UI 或 https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API"^] 以管理用户。

您还可以使用LDAP对选定用户执行身份验证。



== 使用 LDAP

LDAP是一种用于访问分布式目录信息的行业标准协议、也是企业身份验证的常见选择。您可以将Astra控制中心连接到LDAP服务器、以便对选定的Astra用户执行身份验证。从较高层面来看、该配置涉及将Astra与LDAP集成、并定义与LDAP定义对应的Astra用户和组。请参见 https://docs.netapp.com/us-en/astra-automation/workflows_infra/ldap_prepare.html["LDAP 身份验证"^] 有关详细信息 ...



== 邀请用户

客户所有者和管理员可以邀请新用户访问 Astra 控制中心。

.步骤
. 在 * 管理帐户 * 导航区域中，选择 * 帐户 * 。
. 选择 * 用户 * 选项卡。
. 选择 * 邀请用户 * 。
. 输入用户的名称和电子邮件地址。
. 选择具有适当系统权限的用户角色。
+
每个角色都提供以下权限：

+
** * 查看器 * 可以查看资源。
** " 成员 * " 具有 " 查看器 " 角色权限，可以管理应用程序和集群，取消管理应用程序以及删除快照和备份。
** * 管理员 * 具有成员角色权限，可以添加和删除除所有者之外的任何其他用户。
** * 所有者 * 具有管理员角色权限，可以添加和删除任何用户帐户。


. 要为具有成员或查看器角色的用户添加约束，请启用 * 将角色限制为约束条件 * 复选框。
+
有关添加约束的详细信息，请参见 link:manage-roles.html["管理角色"]。

. 选择 * 邀请用户 * 。
+
用户会收到一封电子邮件，告知他们已受邀访问 Astra 控制中心。此电子邮件包含临时密码，需要在首次登录时更改此密码。





== 添加用户

帐户所有者和管理员可以向 Astra 控制中心安装添加更多用户。

.步骤
. 在 * 管理帐户 * 导航区域中，选择 * 帐户 * 。
. 选择 * 用户 * 选项卡。
. 选择 * 添加用户 * 。
. 输入用户的名称，电子邮件地址和临时密码。
+
用户需要在首次登录时更改密码。

. 选择具有适当系统权限的用户角色。
+
每个角色都提供以下权限：

+
** * 查看器 * 可以查看资源。
** " 成员 * " 具有 " 查看器 " 角色权限，可以管理应用程序和集群，取消管理应用程序以及删除快照和备份。
** * 管理员 * 具有成员角色权限，可以添加和删除除所有者之外的任何其他用户。
** * 所有者 * 具有管理员角色权限，可以添加和删除任何用户帐户。


. 要为具有成员或查看器角色的用户添加约束，请启用 * 将角色限制为约束条件 * 复选框。
+
有关添加约束的详细信息，请参见 link:manage-roles.html["管理角色"]。

. 选择 * 添加 * 。




== 管理密码

您可以在 Astra 控制中心管理用户帐户的密码。



=== 更改密码

您可以随时更改用户帐户的密码。

.步骤
. 选择屏幕右上角的用户图标。
. 选择 * 配置文件 * 。
. 从选项菜单的 * 操作 * 列中选择 * 更改密码 * 。
. 输入符合密码要求的密码。
. 再次输入密码进行确认。
. 选择 * 更改密码 * 。




=== 重置其他用户的密码

如果您的帐户具有管理员或所有者角色权限，则可以重置其他用户帐户以及您自己的帐户的密码。重置密码时，您需要分配一个临时密码，用户必须在登录时更改此密码。

.步骤
. 在 * 管理帐户 * 导航区域中，选择 * 帐户 * 。
. 选择 * 操作 * 下拉列表。
. 选择 * 重置密码 * 。
. 输入符合密码要求的临时密码。
. 再次输入密码进行确认。
+

NOTE: 用户下次登录时，系统将提示用户更改密码。

. 选择 * 重置密码 * 。




== 更改用户的角色

具有所有者角色的用户可以更改所有用户的角色，而具有管理员角色的用户可以更改具有管理员，成员或查看器角色的用户的角色。

.步骤
. 在 * 管理帐户 * 导航区域中，选择 * 帐户 * 。
. 选择 * 操作 * 下拉列表。
. 选择 * 编辑角色 * 。
. 选择一个新角色。
. 要对角色应用约束，请启用 * 将角色限制为约束条件 * 复选框，然后从列表中选择一个约束条件。
+
如果没有限制，您可以添加限制。有关详细信息，请参见 link:manage-roles.html["管理角色"]。

. 选择 * 确认 * 。


Astra 控制中心会根据您选择的新角色更新用户的权限。



== 删除用户

具有所有者或管理员角色的用户可以随时从帐户中删除其他用户。

.步骤
. 在 * 管理帐户 * 导航区域中，选择 * 帐户 * 。
. 在 * 用户 * 选项卡中，选中要删除的每个用户所在行中的复选框。
. 从选项菜单的 * 操作 * 列中，选择 * 删除用户 / 秒 * 。
. 出现提示时，键入单词 "remove" 并选择 * 是，删除用户 * 以确认删除。


Astra 控制中心从帐户中删除用户。
