---
sidebar: sidebar 
permalink: use/manage-local-users-and-roles.html 
keywords: add users, edit users, remove users, delete users, manage roles 
summary: 管理Astra控制中心系统上的用户和角色。 
---
= 管理本地用户和角色
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
您可以使用Astra Control UI添加、删除和编辑Astra Control Center安装的用户。您可以使用 Astra Control UI 或 https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API"^] 以管理用户。

您还可以使用LDAP对选定用户执行身份验证。



== 使用 LDAP

LDAP是一种用于访问分布式目录信息的行业标准协议、也是企业身份验证的常见选择。您可以将Astra控制中心连接到LDAP服务器、以便对选定的Astra控制用户执行身份验证。从较高层面来看、该配置涉及将Astra与LDAP集成、并定义与LDAP定义对应的Astra Control用户和组。您可以使用Astra Control API或Web UI配置LDAP身份验证以及LDAP用户和组。有关详细信息、请参见以下文档：

* https://docs.netapp.com/us-en/astra-automation/workflows_infra/ldap_prepare.html["使用Astra Control API管理远程身份验证和用户"^]
* link:manage-remote-users-groups.html["使用Astra Control UI管理远程用户和组"]
* link:manage-remote-authentication.html["使用Astra Control UI管理远程身份验证"]




== 添加用户

帐户所有者和管理员可以向 Astra 控制中心安装添加更多用户。

.步骤
. 在 * 管理帐户 * 导航区域中，选择 * 帐户 * 。
. 选择 * 用户 * 选项卡。
. 选择 * 添加用户 * 。
. 输入用户的名称，电子邮件地址和临时密码。
+
用户需要在首次登录时更改密码。

. 选择具有适当系统权限的用户角色。
+
每个角色都提供以下权限：

+
** * 查看器 * 可以查看资源。
** " 成员 * " 具有 " 查看器 " 角色权限，可以管理应用程序和集群，取消管理应用程序以及删除快照和备份。
** * 管理员 * 具有成员角色权限，可以添加和删除除所有者之外的任何其他用户。
** * 所有者 * 具有管理员角色权限，可以添加和删除任何用户帐户。


. 要为具有成员或查看器角色的用户添加约束，请启用 * 将角色限制为约束条件 * 复选框。
+
有关添加约束的详细信息、请参见 link:manage-local-users-and-roles.html["管理本地用户和角色"]。

. 选择 * 添加 * 。




== 管理密码

您可以在 Astra 控制中心管理用户帐户的密码。



=== 更改密码

您可以随时更改用户帐户的密码。

.步骤
. 选择屏幕右上角的用户图标。
. 选择 * 配置文件 * 。
. 从选项菜单的 * 操作 * 列中选择 * 更改密码 * 。
. 输入符合密码要求的密码。
. 再次输入密码进行确认。
. 选择 * 更改密码 * 。




=== 重置其他用户的密码

如果您的帐户具有管理员或所有者角色权限，则可以重置其他用户帐户以及您自己的帐户的密码。重置密码时，您需要分配一个临时密码，用户必须在登录时更改此密码。

.步骤
. 在 * 管理帐户 * 导航区域中，选择 * 帐户 * 。
. 选择 * 操作 * 下拉列表。
. 选择 * 重置密码 * 。
. 输入符合密码要求的临时密码。
. 再次输入密码进行确认。
+

NOTE: 用户下次登录时，系统将提示用户更改密码。

. 选择 * 重置密码 * 。




== 删除用户

具有所有者或管理员角色的用户可以随时从帐户中删除其他用户。

.步骤
. 在 * 管理帐户 * 导航区域中，选择 * 帐户 * 。
. 在 * 用户 * 选项卡中，选中要删除的每个用户所在行中的复选框。
. 从选项菜单的 * 操作 * 列中，选择 * 删除用户 / 秒 * 。
. 出现提示时，键入单词 "remove" 并选择 * 是，删除用户 * 以确认删除。


.结果
Astra 控制中心从帐户中删除用户。



== 管理角色

您可以通过添加命名空间限制并将用户角色限制为这些限制来管理角色。这样，您就可以控制对组织内资源的访问。您可以使用 Astra Control UI 或 https://docs.netapp.com/us-en/astra-automation/index.html["Astra Control API"^] 以管理角色。



=== 向角色添加命名空间限制

管理员或所有者用户可以向成员或查看器角色添加命名空间限制。

.步骤
. 在 * 管理帐户 * 导航区域中，选择 * 帐户 * 。
. 选择 * 用户 * 选项卡。
. 在 * 操作 * 列中，为具有成员或查看器角色的用户选择菜单按钮。
. 选择 * 编辑角色 * 。
. 启用 * 将角色限制为约束条件 * 复选框。
+
此复选框仅适用于 " 成员 " 或 " 查看器 " 角色。您可以从 * 角色 * 下拉列表中选择其他角色。

. 选择 * 添加约束 * 。
+
您可以按命名空间或命名空间标签查看可用约束的列表。

. 在 * 约束类型 * 下拉列表中，根据命名空间的配置方式选择 * Kubernetes 命名空间 * 或 * Kubernetes 命名空间标签 * 。
. 从列表中选择一个或多个命名空间或标签，以构成一个限制，将角色限制为这些命名空间。
. 选择 * 确认 * 。
+
"* 编辑角色 * " 页面将显示您为此角色选择的约束列表。

. 选择 * 确认 * 。
+
在 * 帐户 * 页面上，您可以在 * 角色 * 列中查看任何成员或查看器角色的限制。




NOTE: 如果为某个角色启用了限制并选择了 * 确认 * 而未添加任何限制，则该角色将被视为具有完全限制（该角色将被拒绝访问分配给命名空间的任何资源）。



=== 从角色中删除命名空间限制

管理员或所有者用户可以从角色中删除命名空间限制。

.步骤
. 在 * 管理帐户 * 导航区域中，选择 * 帐户 * 。
. 选择 * 用户 * 选项卡。
. 在 * 操作 * 列中，为具有成员或查看器角色且具有活动约束的用户选择菜单按钮。
. 选择 * 编辑角色 * 。
+
"* 编辑角色 " 对话框显示角色的活动约束。

. 选择需要删除的约束右侧的 * X * 。
. 选择 * 确认 * 。




== 有关详细信息 ...

* link:../concepts/user-roles-namespaces.html["用户角色和命名空间"]

