---
sidebar: sidebar 
permalink: use/manage-remote-users-groups.html 
keywords: import, import users, search, search users, groups, import groups 
summary: 管理Astra控制中心系统上的远程LDAP用户和组。 
---
= 管理远程用户和组
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
如果您已在Astra Control系统上启用LDAP身份验证、则可以搜索LDAP用户和组、并将其包含在系统的已批准用户中。



== 添加远程用户

帐户所有者和管理员可以向Astra Control添加远程用户。


NOTE: 如果系统上已存在具有相同电子邮件地址的本地用户、则无法添加远程用户。要将此用户添加为远程用户、请先从系统中删除此本地用户。


IMPORTANT: Astra控制中心使用ldap"mail"属性中的电子邮件地址搜索和跟踪远程用户。此属性可能是目录中的可选字段或空字段。对于要显示在Astra控制中心的任何远程用户、此字段中必须存在电子邮件地址。此电子邮件地址在Astra控制中心中用作用户名进行身份验证。

.步骤
. 转到*帐户*区域。
. 选择*用户和组*选项卡。
. 在页面最右侧、选择*远程用户*。
. 选择 * 添加 * 。
. 或者、也可以通过在*按电子邮件筛选*字段中输入用户的电子邮件地址来搜索LDAP用户。
. 从列表中选择一个或多个用户。
. 为用户分配角色。
+

NOTE: 如果您为用户和用户组分配不同的角色、则优先使用较为宽松的角色。

. (可选)为此用户分配一个或多个命名空间约束、然后选择*将角色限制为约束条件*以强制实施这些限制。您可以通过选择*添加约束*来添加新的命名空间约束。
+

NOTE: 如果通过LDAP组成员资格为用户分配了多个角色、则只有最宽松角色中的限制才会生效。例如、如果具有本地查看器角色的用户加入了绑定到成员角色的三个组、则成员角色的约束之和将生效、而查看器角色的任何约束将被忽略。

. 选择 * 添加 * 。


.结果
新用户将显示在远程用户列表中。在此列表中、您可以查看用户的活动约束、并从*操作*菜单管理用户。



== 添加远程组

要一次性添加多个远程用户、帐户所有者和管理员可以向Astra Control添加远程组。添加远程组时、该组中的所有远程用户都会添加到Astra Control并继承相同的角色。

.步骤
. 转到*帐户*区域。
. 选择*用户和组*选项卡。
. 在页面最右侧、选择*远程组*。
. 选择 * 添加 * 。
+
在此窗口中、您可以看到Astra Control从目录中检索到的LDAP组的公用名和可分辨名称列表。

. 或者、也可以在*按公用名筛选*字段中输入组的公用名来搜索LDAP组。
. 从列表中选择一个或多个组。
. 为组分配角色。
+

NOTE: 您选择的角色将分配给此组中的所有用户。如果您为用户和用户组分配不同的角色、则优先使用较为宽松的角色。

. (可选)为此组分配一个或多个命名空间约束、然后选择*将角色限制为约束条件*以强制实施这些限制。您可以通过选择*添加约束*来添加新的命名空间约束。
+

NOTE: 如果通过LDAP组成员资格为用户分配了多个角色、则只有最宽松角色中的限制才会生效。例如、如果具有本地查看器角色的用户加入了绑定到成员角色的三个组、则成员角色的约束之和将生效、而查看器角色的任何约束将被忽略。

. 选择 * 添加 * 。


.结果
新组将显示在远程组列表中、而此组中的所有远程用户将显示在远程用户列表中。在此列表中、您可以查看有关该组的详细信息、并从*操作*菜单管理该组。
