---
sidebar: sidebar 
permalink: use/upgrade-acc.html 
keywords: astra upgrade, upgrade astra control center, how to upgrade astra control, update 
summary: 要升级 Astra 控制中心，您需要下载此捆绑包并按照所述步骤进行升级。 
---
= 升级 Astra 控制中心
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
要升级Astra控制中心、请从NetApp 支持站点 下载安装包并完成以下说明。您可以使用此操作步骤在互联网连接或通风环境中升级 Astra 控制中心。

.您需要什么？ #8217 ；将需要什么
* 升级之前、请参见 link:../get-started/requirements.html#operational-environment-requirements["操作环境要求"^] 确保您的环境仍满足Astra Control Center部署的最低要求。您的环境应具有以下内容：
+
** 支持的Astra Trident版本要确定您正在运行的版本、请对现有的Astra控制中心运行以下命令：
+
[listing]
----
kubectl get tridentversion -n trident
----
+
请参见 https://docs.netapp.com/us-en/trident/trident-managing-k8s/upgrade-trident.html#determine-the-version-to-upgrade-to["Astra Trident 文档"] 从旧版本升级。

+

WARNING: 要升级到Kubernetes 1.25、您必须升级到Astra Trident 22.10 *先前版本*。

** 支持的Kubernetes分发版要确定您运行的版本、请对现有Astra控制中心运行以下命令： `kubectl get nodes -o wide`
** 有足够的集群资源来确定集群资源、请在现有Astra控制中心集群中运行以下命令： `kubectl describe node <node name>`
** 可用于推送和上传Astra控制中心映像的注册表
** 默认存储类要确定默认存储类、请对现有Astra控制中心运行以下命令： `kubectl get storageclass`


* (仅限OpenShift)确保所有集群操作员均处于运行状况良好且可用。
+
[listing]
----
kubectl get clusteroperators
----
* 确保所有 API 服务均处于运行状况良好且可用。
+
[listing]
----
kubectl get apiservices
----
* 在开始升级之前、请从Astra控制中心用户界面中注销。


Astra 控制中心升级过程将指导您完成以下高级步骤：

*  the Astra Control Center bundle
*  the bundle
*  the images to your local registry
*  the updated Astra Control Center operator
*  Astra Control Center
*  system status



IMPORTANT: 请勿删除Astra Control Center运算符(例如、 `kubectl delete -f astra_control_center_operator_deploy.yaml`)、以避免删除Pod。


TIP: 如果计划，备份和快照未运行，请在维护窗口中执行升级。



== 下载 Astra Control Center 捆绑包

. 从下载Astra控制中心捆绑包 https://mysupport.netapp.com/site/products/all/details/astra-control-center/downloads-tab["NetApp 支持站点"^]。文件名类似于以下内容： `astra-control-center-[version].tar.gz`。
. （可选）验证捆绑包的签名：
+
[listing]
----
openssl dgst -sha256 -verify AstraControlCenter-public.pub -signature astra-control-center-[version].tar.gz.sig astra-control-center-[version].tar.gz
----




== 打开捆绑包的包装

. 提取映像：
+
[listing]
----
tar -vxzf astra-control-center-[version].tar.gz
----




== 确认已安装NetApp Astra kubectl插件

NetApp Astra kubectl命令行插件可节省执行与部署和升级Astra控制中心相关的常见任务所需的时间。

. 使用以下命令确定是否已安装此插件：
+
[listing]
----
kubectl astra
----


此命令应提供kubectl插件帮助。如果命令返回错误、请使用这些安装插件 link:../get-started/install_acc.html#install-the-netapp-astra-kubectl-plugin["说明"]。



== 将映像添加到本地注册表

. 为容器引擎完成相应的步骤顺序：


[role="tabbed-block"]
====
.Docker
--
. 更改为 `acc` 从tar包中提取的目录：
+
示例



[listing]
----
cd ../acc
----
. 将Astra Control Center映像目录中的软件包映像推送到本地注册表。在运行命令之前、请执行以下替换操作：
+
** 将<BUNDLE_FILE> 替换为Astra Control捆绑包文件的名称 (`acc.manifest.yaml`）。
** 将<MY_FULL_REGISTRY_PATH> 替换为Docker存储库的URL；例如 https://exampledownloads.jfrog.io/docker-astra-control/v1/[]。
** 将<MY_REGISTRY_USER> 替换为用户名。
** 将<MY_REGISTRY_TOKEN> 替换为注册表的授权令牌。
+
[source, console]
----
kubectl astra packages push-images -m <BUNDLE_FILE> -r <MY_FULL_REGISTRY_PATH> -u <MY_REGISTRY_USER> -p <MY_REGISTRY_TOKEN>
----




--
.Podman
--
. 登录到注册表：
+
[source, console]
----
podman login <MY_FULL_REGISTRY_PATH>
----
. 运行以下脚本、按照注释中的说明替换<your_registry>：
+
[source, console]
----
# You need to be at the root of the tarball.
# You should see these files to confirm correct location:
#   acc.manifest.yaml
#   acc/

# Replace <YOUR_REGISTRY> with your own registry (e.g registry.customer.com or registry.customer.com/testing, etc..)
export REGISTRY=<YOUR_REGISTRY>
export PACKAGENAME=acc
export PACKAGEVERSION=22.11.0-82
export DIRECTORYNAME=acc
for astraImageFile in $(ls ${DIRECTORYNAME}/images/*.tar) ; do
  # Load to local cache
  astraImage=$(podman load --input ${astraImageFile} | sed 's/Loaded image(s): //')

  # Remove path and keep imageName.
  astraImageNoPath=$(echo ${astraImage} | sed 's:.*/::')

  # Tag with local image repo.
  podman tag ${astraImage} ${REGISTRY}/netapp/astra/${PACKAGENAME}/${PACKAGEVERSION}/${astraImageNoPath}

  # Push to the local repo.
  podman push ${REGISTRY}/netapp/astra/${PACKAGENAME}/${PACKAGEVERSION}/${astraImageNoPath}
done
----


--
====


== 安装更新后的 Astra 控制中心操作员

. 更改目录：
+
[listing]
----
cd manifests
----
. 编辑 Astra 控制中心操作员部署 YAML （`Astra_control_center_operator_deploy.yaml` ）以参考您的本地注册表和机密。
+
[listing]
----
vim astra_control_center_operator_deploy.yaml
----
+
.. 如果您使用的注册表需要身份验证、请替换或编辑的默认行 `imagePullSecrets: []` 使用以下命令：
+
[listing]
----
imagePullSecrets:
- name: <astra-registry-cred_or_custom_name_of_secret>
----
.. 更改 `[your_registry_path]` 。 `kube-rbac-proxy` 将映像推送到注册表路径中  the images to your local registry,上一步。
.. 更改 `[your_registry_path]` 。 `acc-operator` 将映像推送到注册表路径中  the images to your local registry,上一步。
.. 将以下值添加到 `env` 部分：
+
[listing]
----
- name: ACCOP_HELM_UPGRADETIMEOUT
  value: 300m
----
+
[listing, subs="+quotes"]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: acc-operator-controller-manager
  namespace: netapp-acc-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        *image: [your_registry_path]/kube-rbac-proxy:v4.8.0*
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        env:
        - name: ACCOP_LOG_LEVEL
          value: "2"
        *- name: ACCOP_HELM_UPGRADETIMEOUT*
          *value: 300m*
        *image: [your_registry_path]/acc-operator:[version x.y.z]*
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 300m
            memory: 750Mi
          requests:
            cpu: 100m
            memory: 75Mi
        securityContext:
          allowPrivilegeEscalation: false
      *imagePullSecrets: []*
      securityContext:
        runAsUser: 65532
      terminationGracePeriodSeconds: 10
----


. 安装更新后的 Astra 控制中心操作员：
+
[listing]
----
kubectl apply -f astra_control_center_operator_deploy.yaml
----
+
响应示例：

+
[listing]
----
namespace/netapp-acc-operator unchanged
customresourcedefinition.apiextensions.k8s.io/astracontrolcenters.astra.netapp.io configured
role.rbac.authorization.k8s.io/acc-operator-leader-election-role unchanged
clusterrole.rbac.authorization.k8s.io/acc-operator-manager-role configured
clusterrole.rbac.authorization.k8s.io/acc-operator-metrics-reader unchanged
clusterrole.rbac.authorization.k8s.io/acc-operator-proxy-role unchanged
rolebinding.rbac.authorization.k8s.io/acc-operator-leader-election-rolebinding unchanged
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-manager-rolebinding configured
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-proxy-rolebinding unchanged
configmap/acc-operator-manager-config unchanged
service/acc-operator-controller-manager-metrics-service unchanged
deployment.apps/acc-operator-controller-manager configured
----
. 验证Pod是否正在运行：
+
[listing]
----
kubectl get pods -n netapp-acc-operator
----




== 升级 Astra 控制中心

. 编辑Astra Control Center自定义资源(CR)：
+
[listing]
----
kubectl edit AstraControlCenter -n [netapp-acc or custom namespace]
----
. 更改Astra版本号 (`astraVersion` 在中 `Spec`)升级到要升级到的版本：
+
[listing, subs="+quotes"]
----
spec:
  accountName: "Example"
  *astraVersion: "[Version number]"*
----
. 验证您的映像注册表路径是否与您在中将映像推送到的注册表路径匹配  the images to your local registry,上一步。更新 `imageRegistry` 在中 `Spec` 注册表自上次安装以来是否发生了更改。
+
[listing]
----
  imageRegistry:
    name: "[your_registry_path]"
----
. 将以下内容添加到 `CRDs` 中的配置 `Spec`：
+
[listing]
----
crds:
  shouldUpgrade: true
----
. 在 Astra 控制中心 CR 的 `SPec` 内的 `addtionalValues` 中添加以下行：
+
[listing]
----
additionalValues:
    nautilus:
      startupProbe:
        periodSeconds: 30
        failureThreshold: 600
----
+
保存并退出文件编辑器后、将应用所做的更改并开始升级。

. （可选）验证 Pod 是否终止并重新可用：
+
[listing]
----
watch kubectl get pods -n [netapp-acc or custom namespace]
----
. 等待Astra状态条件指示升级已完成且准备就绪 (`True`）：
+
[listing]
----
kubectl get AstraControlCenter -n [netapp-acc or custom namespace]
----
+
响应：

+
[listing]
----
NAME    UUID                                      VERSION     ADDRESS         READY
astra   9aa5fdae-4214-4cb7-9976-5d8b4c0ce27f  22.11.0-24  10.111.111.111  True
----
+

NOTE: 要在操作期间监控升级状态、请运行以下命令： `kubectl get AstraControlCenter -o yaml -n [netapp-acc or custom namespace]`

+

NOTE: 要检查Astra控制中心操作员日志、请运行以下命令：
`kubectl logs deploy/acc-operator-controller-manager -n netapp-acc-operator -c manager -f`





== 验证系统状态

. 登录到 Astra 控制中心。
. 验证此版本是否已升级。请参见用户界面中的*支持*页面。
. 验证所有受管集群和应用程序是否仍存在并受到保护。

