---
sidebar: sidebar 
permalink: use/view-apps.html 
keywords: view app, view app status, view app protection status, view app pods, view persistent storage 
summary: 开始管理某个应用程序后， Astra Control 会提供有关该应用程序的详细信息，您可以通过这些详细信息来确定其状态，保护状态， Pod ，永久性存储等。 
---
= 查看应用程序的运行状况和详细信息
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
开始管理某个应用程序后， Astra Control 会提供有关该应用程序的详细信息，使您能够确定其状态（是否运行正常），保护状态（是否在发生故障时受到全面保护）， Pod ，永久性存储等。

.步骤
. 在 Astra 控制中心 UI 中，选择 * 应用程序 * ，然后选择应用程序的名称。
. 查看相关信息。
+
** *应用程序状态*：提供反映应用程序在Kubernetes中的状态的状态。例如， Pod 和永久性卷是否联机？如果某个应用程序运行状况不正常，您需要查看 Kubernetes 日志，对集群上的问题描述进行故障排除。Astra 不会提供任何信息来帮助您修复损坏的应用程序。
** *应用程序保护状态*：提供应用程序的保护程度状态：
+
*** * 完全保护 * ：应用程序具有一个活动备份计划，并且备份成功完成不到一周
*** * 部分保护 * ：应用程序具有活动备份计划，活动快照计划或成功备份或快照
*** * 未受保护 * ：既不受完全保护也不受部分保护的应用程序。
+
_You can't be Fully protected until you have a recent backup_ 。这一点非常重要，因为备份存储在对象存储中，而不是永久性卷。如果发生故障或意外事件会擦除集群及其永久性存储，则需要备份才能恢复。快照无法让您恢复。



** *概述*：有关与应用程序关联的Pod的状态的信息。
** *数据保护*：用于配置数据保护策略以及查看现有快照和备份。
** *存储*：显示应用程序级别的永久性卷。从 Kubernetes 集群的角度来看，永久性卷的状态。
** *资源*：用于验证正在备份和管理哪些资源。
** *活动*：显示与应用程序相关的活动。
+

NOTE: 您还可以从 Astra 控制中心 * 信息板 * 开始查看应用程序信息。在 * 资源摘要 * 下的 * 应用程序 * 选项卡上，您可以选择受管应用程序，此操作将转到 * 应用程序 * 页面。进入 * 应用程序 * 页面后，请按照上述步骤进行操作。




