---
sidebar: sidebar 
permalink: get-started/requirements.html 
keywords: what are astra kubernetes requirements, astra control requirements, astra supported versions, apps, supported apps, mariadb, mysql, postgres, kubernetes version, ubuntu, image type, networking, environment, operational, operational environment, hosting, host, cluster, clusters, tanzu, tkg, tkgi, grid, kubernetes, k8s 
summary: 通过验证对 Kubernetes 集群，应用程序和 Web 浏览器的支持，开始使用 Astra 控制中心。 
---
= Astra 控制中心要求
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
首先验证操作环境，应用程序集群，应用程序，许可证和 Web 浏览器的就绪情况。确保您的环境满足这些要求、以部署和运行Astra Control Center。



== 支持的主机集群Kubennetes环境

Astra Control Center已通过以下Kubenetes主机环境的验证：


NOTE: 确保您选择托管Astra Control Center的Kubennet环境满足环境官方文档中列出的基本资源要求。

|===
| 主机集群上的Kubnetes分发 | 支持的版本 


| 基于Azure堆栈HCI的Azure Kubnetes Service | 采用AKS 1.24.x和1.25x的Azure Stack HCI 21H2和22H2 


| Google Anthos | 1.15至1.16 (请参见 <<Google Anthos入口要求>>） 


| Kubnetes (上游) | 1.26至1.28 


| Rancher Kubernetes Engine （ RKE） | RKE 1.3与R能 手管理器2.6
RKE 1.4与R能 手管理器2.7
RKE 2 (v1.24.x)与R能 手2.6
RKE 2 (v1.26.x)与R9cher 2.7 


| Red Hat OpenShift 容器平台 | 4.11至4.13 


| VMware Tanzu Kubernetes Grid Integrated Edition | 1.16.x (请参见 <<主机集群资源要求>>） 
|===


== 主机集群资源要求

除了环境的资源要求之外， Astra 控制中心还需要以下资源：


NOTE: 这些要求假定 Astra 控制中心是运行环境中唯一运行的应用程序。如果环境运行的是其他应用程序，请相应地调整这些最低要求。

* *CPU扩展*：托管环境中所有节点的CPU都必须启用AVX扩展。
* *工作节点*：总共至少3个工作节点、每个节点具有4个CPU核心和12 GB RAM
* *VMware Tanzu Kubernetes Grid集群要求*：在VMware Tanzu Kubernetes Grid (TKG)或Tanzu Kubernetes Grid Integrated Edition (TKGi)集群上托管Astra Control Center时，请记住以下注意事项。
+
** 默认的 VMware TKG 和 TKGi 配置文件令牌将在部署后 10 小时过期。如果您使用的是 Tanzu 产品组合，则必须使用未过期的令牌生成 Tanzu Kubernetes 集群配置文件，以防止 Astra 控制中心与受管应用程序集群之间出现连接问题。有关说明，请访问 https://docs.vmware.com/en/VMware-NSX-T-Data-Center/3.2/nsx-application-platform/GUID-52A52C0B-9575-43B6-ADE2-E8640E22C29F.html["VMware NSX-T 数据中心产品文档。"^]
** 使用 `kubectl get nsxlbmonitors -A` 命令以查看是否已将服务监控器配置为接受传入流量。如果存在一个，则不应安装 MetalLB ，因为现有服务监控器将覆盖任何新的负载平衡器配置。
** 在任何要由 Astra Control 管理的应用程序集群上禁用 TKG 或 TKGi 默认存储类强制实施。您可以通过编辑来执行此操作 `TanzuKubernetesCluster` 命名空间集群上的资源。
** 在 TKG 或 TKGi 环境中部署 Astra 控制中心时，请注意 Astra Trident 的特定要求。有关详细信息，请参见 https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy.html#other-known-configuration-options["Astra Trident 文档"^]。






== 服务网格要求

强烈建议在Astra Control Center主机集群上安装受支持的V社会 版本的Isio服务网格。请参见 https://istio.io/latest/docs/releases/supported-releases/["支持的版本"^] 支持的伊斯托伊奥版本。Itio服务网格的品牌版本(例如OpenShift Service Mesh)未通过Astra Control Center的验证。

要将Astra Control Center与主机集群上安装的Isio服务网格集成、必须在Astra Control Center中进行集成 link:../get-started/install_acc.html["安装"] 而不是独立于此过程。


NOTE: 如果在主机集群上安装Astra Control Service而不配置服务网格、则可能会产生严重的安全影响。



== Astra Trident 要求

确保您满足以下特定于您环境需求的Astra三项要求：

* *与Astra Control Center*一起使用的最低版本：已安装并配置Astra Drident 23.01或更高版本
* *采用Astra三端的ONTAP 配置*：
+
** *存储类*：在集群上至少配置一个Astra三端存储类。如果配置了默认存储类、请确保它是唯一具有默认指定的存储类。
** *存储驱动程序和工作节点*：确保为集群中的工作节点配置适当的存储驱动程序，以便Pod可以与后端存储进行交互。Astra 控制中心支持由 Astra Trident 提供的以下 ONTAP 驱动程序：
+
*** `ontap-nas`
*** `ontap-san`
*** `ontap-san-economy` (此存储类类型不支持应用程序复制)
*** `ontap-nas-economy` (快照、复制策略和保护策略不适用于此存储类类型)








== Asta Control配置程序

要使用Astra Control配置程序高级存储功能、必须安装Astra Trident 23.10或更高版本并启用 link:../use/enable-acp.html["Astra Control配置程序功能"]。



== 存储后端

请确保您有一个受支持的后端、并具有足够的容量。

* *所需存储后端容量*：至少500 GB可用
* *支持的后端*：Astra Control Center支持以下存储后端：
+
** NetApp ONTAP 9.9.1或更高版本的AFF、FAS和ASA系统
** NetApp ONTAP Select 9.9.1或更高版本
** NetApp Cloud Volumes ONTAP 9.9.1或更高版本
** Longhorn 1.5.0或更高版本
+
*** 需要手动创建卷SnapshotClass对象。请参见 https://longhorn.io/docs/1.5.0/snapshots-and-backups/csi-snapshot-support/csi-volume-snapshot-associated-with-longhorn-snapshot/#create-a-csi-volumesnapshot-associated-with-longhorn-snapshot["Longhorn文档"^] 有关说明，请参见。


** NetApp MetroCluster
+
*** 受管Kubbernetes集群必须采用延伸型配置。


** 支持的云提供商提供存储后端






=== ONTAP 许可证

要使用Astra控制中心、请根据您需要完成的任务、验证您是否具有以下ONTAP 许可证：

* FlexClone
* SnapMirror：可选。只有在使用SnapMirror技术复制到远程系统时才需要。请参见 https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-licensing-concept.html["SnapMirror许可证信息"^]。
* S3许可证：可选。只有ONTAP S3存储分段才需要


要检查ONTAP 系统是否具有所需的许可证、请参见 https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html["管理ONTAP 许可证"^]。



=== NetApp MetroCluster

使用NetApp MetroCluster作为存储后端时、您需要执行以下操作：

* 在您使用的Asta三端驱动程序中、将SVM管理LIF指定为后端选项
* 确保您拥有相应的ONTAP许可证


要配置MetroCluster LIF、请参阅Astra三端驱动程序文档、了解有关每个驱动程序的详细信息：

* https://docs.netapp.com/us-en/trident/trident-use/ontap-san-examples.html["SAN"^]
* https://docs.netapp.com/us-en/trident/trident-use/ontap-nas-examples.html["NAS"^]




== 映像注册表

您必须具有现有的私有Docker映像注册表、可以将Astra Control Center构建映像推送到该注册表中。您需要提供要将映像上传到的映像注册表的 URL 。



== Asta Control Center许可证

Astra Control Center需要Astra Control Center许可证。安装Astra Control Center时、已激活4、800个CPU单元的嵌入式90天评估版许可证。如果您需要更多容量或不同的评估条款、或者要升级到完整许可证、则可以从NetApp获得不同的评估许可证或完整许可证。您需要一个许可证来保护应用程序和数据。

您可以通过注册获取免费试用版来试用Astra Control Center。您可以通过注册进行注册 link:https://bluexp.netapp.com/astra-register["此处"^]。

要设置许可证、请参见 link:setup_overview.html["使用 90 天评估许可证"^]。

要了解有关许可证工作原理的详细信息、请参见 link:../concepts/licensing.html["许可"^]。



== 网络要求

配置操作环境以确保Astra Control Center可以正确通信。需要以下网络配置：

* *FQDN地址*:您必须拥有Astra Control Center的FQDN地址。
* *访问互联网*：您应确定是否可以从外部访问互联网。否则，某些功能可能会受到限制，例如从 NetApp Cloud Insights 接收监控和指标数据或向发送支持包 https://mysupport.netapp.com/site/["NetApp 支持站点"^]。
* *端口访问*：Astra Control Center的运行环境使用以下TCP端口进行通信。您应确保允许这些端口通过任何防火墙，并将防火墙配置为允许来自 Astra 网络的任何 HTTPS 传出流量。某些端口需要在托管 Astra 控制中心的环境与每个受管集群之间进行双向连接（请在适用时注明）。



NOTE: 您可以在双堆栈 Kubernetes 集群中部署 Astra 控制中心，而 Astra 控制中心则可以管理为双堆栈操作配置的应用程序和存储后端。有关双堆栈集群要求的详细信息，请参见 https://kubernetes.io/docs/concepts/services-networking/dual-stack/["Kubernetes 文档"^]。

|===
| 源 | 目标 | Port | 协议 | 目的 


| 客户端 PC | Astra 控制中心 | 443. | HTTPS | UI / API 访问 - 确保托管 Astra 控制中心的集群与每个受管集群之间的此端口是双向开放的 


| 指标使用者 | Astra 控制中心工作节点 | 9090 | HTTPS | 指标数据通信—确保每个受管集群都可以访问托管 Astra 控制中心的集群上的此端口 （需要双向通信） 


| Astra 控制中心 | 托管 Cloud Insights 服务  | 443. | HTTPS | Cloud Insights 通信 


| Astra 控制中心 | Amazon S3 存储分段提供商 | 443. | HTTPS | Amazon S3 存储通信 


| Astra 控制中心 | NetApp AutoSupport  | 443. | HTTPS | NetApp AutoSupport 通信 
|===


== 内部 Kubernetes 集群的传入

您可以选择 Astra 控制中心使用的网络传入类型。默认情况下， Astra 控制中心会将 Astra 控制中心网关（ service/traefik ）部署为集群范围的资源。如果您的环境允许使用服务负载平衡器，则 Astra 控制中心也支持使用服务负载平衡器。如果您希望使用服务负载平衡器、但尚未配置此平衡器、则可以使用MetalLB负载平衡器自动为该服务分配外部IP地址。在内部 DNS 服务器配置中，您应将为 Astra 控制中心选择的 DNS 名称指向负载平衡的 IP 地址。


NOTE: 负载平衡器应使用与Astra控制中心工作节点IP地址位于同一子网中的IP地址。

有关详细信息，请参见 link:../get-started/install_acc.html#set-up-ingress-for-load-balancing["设置传入以进行负载平衡"^]。



=== Google Anthos入口要求

如果在Google Anthos集群上托管Astra Control Center、请注意、默认情况下、Google Anthos包括MetalLB负载平衡器和Istio入口服务、您只需在安装期间使用Astra Control Center的通用入口功能即可。请参见 link:install_acc.html#configure-astra-control-center["配置 Astra 控制中心"^] 了解详细信息。



== 支持的 Web 浏览器

Astra 控制中心支持最新版本的 Firefox ， Safari 和 Chrome ，最小分辨率为 1280 x 720 。



== 应用程序集群的其他要求

如果您计划使用以下Astra控制中心功能、请记住这些要求：

* *应用程序集群要求*： link:../get-started/setup_overview.html#prepare-your-environment-for-cluster-management-using-astra-control["集群管理要求"^]
+
** *受管应用程序要求*： link:../use/manage-apps.html#application-management-requirements["应用程序管理要求"^]
** *应用程序复制的其他要求*： link:../use/replicate_snapmirror.html#replication-prerequisites["复制前提条件"^]






== 下一步行动

查看 link:quick-start.html["快速入门"^] 概述。
