---
sidebar: sidebar 
permalink: get-started/requirements.html 
keywords: what are astra kubernetes requirements, astra control requirements, astra supported versions, apps, supported apps, mariadb, mysql, postgres, kubernetes version, ubuntu, image type, networking, environment, operational, operational environment, hosting, host, cluster, clusters 
summary: 通过验证对 Kubernetes 集群，应用程序和 Web 浏览器的支持，开始使用 Astra 控制中心。 
---
= Astra 控制中心要求
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


首先验证操作环境，应用程序集群，应用程序，许可证和 Web 浏览器的就绪情况。



== 操作环境要求

Astra 控制中心需要以下类型的操作环境之一：

* Red Hat OpenShift 容器平台 4.6-8 ， 4.7 或 4.8
* Rancher 2.5
* Kubernetes 1.19 到 1.21 （包括 1.21.x ）


确保您选择托管 Astra 控制中心的操作环境满足环境官方文档中概述的基本资源要求。除了环境的资源要求之外， Astra 控制中心还需要以下资源：

|===
| 组件 | 要求 


| 后端 ONTAP 存储容量 | 至少 300 GB 可用 


| 工作节点 | 总共至少 3 个辅助节点，每个节点有 4 个 CPU 核和 12 GB RAM 


| 负载平衡器 | 服务类型 "loadbalancer" 可用于将传入流量发送到操作环境集群中的服务 


| FQDN 解析 | 一种将 Astra 控制中心的 FQDN 指向负载平衡 IP 地址的方法 


| Astra Trident  a| 
* 如果要使用 NetApp ONTAP 9.5 或更高版本作为存储后端，则已安装并配置 Astra Trident 21.04 或更高版本
* 如果使用 Astra Data Store 预览版作为存储后端，则已安装并配置 Astra Trident 21.10.1 或更高版本


|===

NOTE: 这些要求假定 Astra 控制中心是运行环境中唯一运行的应用程序。如果环境运行的是其他应用程序，请相应地调整这些最低要求。

* * 映像注册表 * ：您必须具有可将 Astra 控制中心构建映像推送到的现有私有 Docker 映像注册表。您需要提供要将映像上传到的映像注册表的 URL 。
* * 天文学 Trident / ONTAP 配置 * ：天文学控制中心要求创建一个存储类并将其设置为默认存储类。Astra 控制中心支持由 Astra Trident 提供的以下 ONTAP 驱动程序：
+
** ontap-NAS
** ontap-nas-flexgroup
** ontap-san
** ontap-san-economy.




[NOTE]
====
在 OpenShift 环境中克隆应用程序期间， Astra Control Center 需要允许 OpenShift 挂载卷并更改文件所有权。因此，您需要配置 ONTAP 卷导出策略以允许执行这些操作。您可以使用以下命令执行此操作：

. `export-policy rule modify -vserver <storage virtual machine name> -policyname <policy name> -ruleindex 1 -superuser sys`
. `export-policy rule modify -vserver <storage virtual machine name> -policyname <policy name> -ruleindex 1 -anon 65534`


====

NOTE: 如果您计划将第二个 OpenShift 操作环境添加为托管计算资源，则需要确保已启用 Astra Trident 卷快照功能。要使用 Astra Trident 启用和测试卷快照， https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html["请参见官方的 Astra Trident 说明"^]。



== 应用程序集群要求

对于计划从 Astra 控制中心管理的集群， Astra 控制中心具有以下要求。如果您计划管理的集群是托管 Astra 控制中心的运行环境集群，则这些要求也适用。

* Kubernetes 的最新版本 https://kubernetes-csi.github.io/docs/snapshot-controller.html["Snapshot 控制器组件"^] 已安装
* Astra Trident https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html["volumesnapshotclass 对象"^] 已由管理员定义
* 集群上存在默认 Kubernetes 存储类
* 至少将一个存储类配置为使用 Astra Trident



NOTE: 您的应用程序集群应具有一个 `kubeconfig.yaml` 文件，该文件仅定义一个 _context_ 元素。请访问的 Kubernetes 文档 https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/["有关创建 kubeconfig 文件的信息"^]。


NOTE: 在 Rancher 环境中管理应用程序集群时，请修改 Rancher 提供的 `kubeconfig` 文件中的应用程序集群默认上下文，以使用控制平面上下文，而不是 Rancher API 服务器上下文。这样可以减少 Rancher API 服务器上的负载并提高性能。



== 应用程序管理要求

Astra Control 具有以下应用程序管理要求：

* * 许可 * ：要使用 Astra 控制中心管理应用程序，您需要获得 Astra 控制中心许可证。
* * 命名空间 * ： Astra Control 要求一个应用程序不能跨越多个命名空间，但一个命名空间可以包含多个应用程序。
* * 存储类 * ：如果您安装的应用程序明确设置了 StorageClass ，并且需要克隆该应用程序，则克隆操作的目标集群必须具有最初指定的 StorageClass 。将显式设置了 StorageClass 的应用程序克隆到不具有相同 StorageClass 的集群将失败。
* * Kubernetes Resources* ：使用非 Astra Control 收集的 Kubernetes 资源的应用程序可能没有完整的应用程序数据管理功能。Astra Control 收集以下 Kubernetes 资源：
+
** ClusterRole
** ClusterRoleBinding.
** 配置映射
** 自定义资源定义
** 自定义资源
** DemonSet
** 部署
** DeploymentConfig
** 传入
** MutatingWebhook
** PersistentVolumeClaim
** POD
** ReplicaSet
** RoleBinding.
** Role
** 路由
** 机密
** 服务
** ServiceAccount
** 状态集
** 验证 Webhook






=== 支持的应用程序安装方法

Astra Control 支持以下应用程序安装方法：

* * 清单文件 * ： Astra Control 支持使用 kubectl 从清单文件安装的应用程序。例如：
+
[listing]
----
kubectl apply -f myapp.yaml
----
* * Helm 3* ：如果使用 Helm 安装应用程序，则 Astra Control 需要 Helm 版本 3 。完全支持管理和克隆随 Helm 3 安装的应用程序（或从 Helm 2 升级到 Helm 3 ）。不支持管理随 Helm 2 安装的应用程序。
* * 操作员部署的应用程序 * ： Astra Control 支持使用命名空间范围的运算符安装的应用程序。以下是已针对此安装模式验证的一些应用程序：
+
** https://github.com/k8ssandra/cass-operator/tree/v1.7.1["Apache K8ssandra"^]
** https://github.com/jenkinsci/kubernetes-operator["Jenkins CI"^]
** https://github.com/percona/percona-xtradb-cluster-operator["Percona XtraDB 集群"^]





NOTE: 操作员及其安装的应用程序必须使用相同的命名空间；您可能需要为操作员修改部署 .yaml 文件，以确保情况确实如此。



== 访问 Internet

您应确定是否可以从外部访问 Internet 。否则，某些功能可能会受到限制，例如从 NetApp Cloud Insights 接收监控和指标数据或向发送支持包 https://mysupport.netapp.com/site/["NetApp 支持站点"^]。



== 许可证

要实现全部功能， Astra 控制中心需要获得 Astra 控制中心许可证。从 NetApp 获取评估版许可证或完整许可证。如果没有许可证，您将无法：

* 定义自定义应用程序
* 为现有应用程序创建快照或克隆
* 配置数据保护策略


如果您要尝试使用 Astra 控制中心，可以 link:setup_overview.html#add-a-full-or-evaluation-license["使用 90 天评估许可证"]。



== 内部 Kubernetes 集群的服务类型 "loadbalancer"

Astra 控制中心使用类型为 "loadbalancer" 的服务（在 Astra 控制中心命名空间中为服务提供服务），并要求为其分配一个可访问的外部 IP 地址。如果您的环境允许使用负载平衡器，但您尚未配置一个负载平衡器，则可以使用 https://docs.netapp.com/us-en/netapp-solutions/containers/rh-os-n_LB_MetalLB.html#installing-the-metallb-load-balancer["元 LB"^] 自动为服务分配外部 IP 地址。在内部 DNS 服务器配置中，您应将为 Astra 控制中心选择的 DNS 名称指向负载平衡的 IP 地址。



== 网络要求

托管 Astra 控制中心的操作环境使用以下 TCP 端口进行通信。您应确保允许这些端口通过任何防火墙，并将防火墙配置为允许来自 Astra 网络的任何 HTTPS 传出流量。某些端口需要在托管 Astra 控制中心的环境与每个受管集群之间进行双向连接（请在适用时注明）。

|===
| 源 | 目标 | Port | 协议 | 目的 


| 客户端 PC | Astra 控制中心 | 443. | HTTPS | UI / API 访问 - 确保托管 Astra 控制中心的集群与每个受管集群之间的此端口是双向开放的 


| 指标使用者 | Astra 控制中心工作节点 | 9090 | HTTPS | 指标数据通信—确保每个受管集群都可以访问托管 Astra 控制中心的集群上的此端口 （需要双向通信） 


| Astra 控制中心 | 托管 Cloud Insights 服务 (https://cloudinsights.netapp.com)[] | 443. | HTTPS | Cloud Insights 通信 


| Astra 控制中心 | Amazon S3 存储分段提供商 (https://my-bucket.s3.us-west-2.amazonaws.com/)[] | 443. | HTTPS | Amazon S3 存储通信 


| Astra 控制中心 | NetApp ActiveIQ (https://activeiq.solidfire.com)[] | 443. | HTTPS | NetApp ActiveIQ 通信 
|===


== 支持的 Web 浏览器

Astra 控制中心支持最新版本的 Firefox ， Safari 和 Chrome ，最小分辨率为 1280 x 720 。



== 下一步行动

查看 link:quick-start.html["快速入门"] 概述。
