---
sidebar: sidebar 
permalink: get-started/requirements.html 
keywords: what are astra kubernetes requirements, astra control requirements, astra supported versions, apps, supported apps, mariadb, mysql, postgres, kubernetes version, ubuntu, image type, networking, environment, operational, operational environment, hosting, host, cluster, clusters, tanzu, tkg, tkgi, grid, kubernetes, k8s 
summary: 通过验证对 Kubernetes 集群，应用程序和 Web 浏览器的支持，开始使用 Astra 控制中心。 
---
= Astra 控制中心要求
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
首先验证操作环境，应用程序集群，应用程序，许可证和 Web 浏览器的就绪情况。

* <<操作环境要求>>
* <<支持的存储后端>>
* <<访问 Internet>>
* <<许可证>>
* <<内部 Kubernetes 集群的传入>>
* <<网络要求>>
* <<支持的 Web 浏览器>>
* <<应用程序集群的其他要求>>
* <<Google Anthos集群要求>>
* <<VMware Tanzu Kubernetes Grid 集群要求>>




== 操作环境要求

Astra控制中心已在以下类型的操作环境中进行了验证：

* 采用Kubernetes 1.22的Cisco IKS
* Google Anthos 1.11或1.12 (请参见 <<Google Anthos集群要求>>）
* Rancher Kubernetes Engine (RKE）：
+
** RKE1.3.12与Rancher 2.6.5和2.6.6
** RKE1.3.13与Rancher 2.6.8
** RKE2 (v1.23.6+rke2r1)与Rancher 2.6.5和2.6.6
** RKE2 (v1.24.x)与Rancher 2.6.8


* Red Hat OpenShift容器平台4.8至4.11
* 上游Kubernetes 1.23到1.25 (Kubernetes 1.25需要Astra Trident 22.10或更高版本)
* VMware Tanzu Kubernetes网格：(请参见 <<VMware Tanzu Kubernetes Grid 集群要求>>）
+
** VMware Tanzu Kubernetes网格1.5
** VMware Tanzu Kubernetes Grid Integrated Edition 1.13和1.14




确保您选择托管 Astra 控制中心的操作环境满足环境官方文档中概述的基本资源要求。除了环境的资源要求之外， Astra 控制中心还需要以下资源：

|===
| 组件 | 要求 


| CPU扩展 | 托管环境中所有节点的CPU必须启用AVX扩展。 


| 存储后端容量 | 至少500 GB可用 


| 工作节点  a| 
总共至少 3 个辅助节点，每个节点有 4 个 CPU 核和 12 GB RAM



| FQDN 地址 | Astra 控制中心的 FQDN 地址 


| Astra Trident  a| 
已为基于SnapMirror的应用程序复制安装Astra Trident 22.01或更高版本并进行了配置Astra Trident 22.07或更高版本已为Kubernetes 1.25集群安装Astra Trident 22.10或更高版本(必须先升级到Astra Trident 22.10、然后再升级到Kubernetes 1.25)

|===

NOTE: 这些要求假定 Astra 控制中心是运行环境中唯一运行的应用程序。如果环境运行的是其他应用程序，请相应地调整这些最低要求。

* * 映像注册表 * ：您必须具有可将 Astra 控制中心构建映像推送到的现有私有 Docker 映像注册表。您需要提供要将映像上传到的映像注册表的 URL 。
* * Astra Trident / ONTAP 配置*：
+
** Astra 控制中心要求创建一个存储类并将其设置为默认存储类。
** 确保集群中的工作节点已配置适当的存储驱动程序、以便Pod可以与后端存储进行交互。Astra 控制中心支持由 Astra Trident 提供的以下 ONTAP 驱动程序：
+
*** ontap-NAS
*** ontap-nas-flexgroup
*** ontap-san
*** ontap-san-economy.(不支持应用程序复制)








== 支持的存储后端

Astra 控制中心支持以下存储后端。

* NetApp ONTAP 9.5 或更高版本的 AFF 和 FAS 系统
* NetApp ONTAP 9.8或更高版本的AFF 和FAS 系统、用于基于SnapMirror的应用程序复制
* NetApp Cloud Volumes ONTAP


要使用Astra控制中心、请根据您需要完成的任务、验证您是否具有以下ONTAP 许可证：

* FlexClone
* SnapMirror：可选。只有在使用SnapMirror技术复制到远程系统时才需要。请参见 https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-licensing-concept.html["SnapMirror许可证信息"^]。
* S3许可证：可选。只有ONTAP S3存储分段才需要


要检查ONTAP 系统是否具有所需的许可证、请参见 https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html["管理ONTAP 许可证"^]。



== 访问 Internet

您应确定是否可以从外部访问 Internet 。否则，某些功能可能会受到限制，例如从 NetApp Cloud Insights 接收监控和指标数据或向发送支持包 https://mysupport.netapp.com/site/["NetApp 支持站点"^]。



== 许可证

要实现全部功能， Astra 控制中心需要获得 Astra 控制中心许可证。从 NetApp 获取评估版许可证或完整许可证。您需要一个许可证来保护应用程序和数据。请参见 link:../concepts/intro.html["Astra控制中心功能"] 了解详细信息。

您可以使用评估版许可证试用Astra控制中心、这样、您可以在自下载此许可证之日起的90天内使用Astra控制中心。您可以通过注册注册注册免费试用版 link:https://cloud.netapp.com/astra-register["此处"^]。

要设置许可证、请参见 link:setup_overview.html["使用 90 天评估许可证"^]。

要了解有关许可证工作原理的详细信息，请参见 link:../concepts/licensing.html["许可"^]。

有关ONTAP 存储后端所需许可证的详细信息、请参见 link:../get-started/requirements.html["支持的存储后端"]。



== 内部 Kubernetes 集群的传入

您可以选择 Astra 控制中心使用的网络传入类型。默认情况下， Astra 控制中心会将 Astra 控制中心网关（ service/traefik ）部署为集群范围的资源。如果您的环境允许使用服务负载平衡器，则 Astra 控制中心也支持使用服务负载平衡器。如果您希望使用服务负载平衡器、但尚未配置此平衡器、则可以使用MetalLB负载平衡器自动为该服务分配外部IP地址。在内部 DNS 服务器配置中，您应将为 Astra 控制中心选择的 DNS 名称指向负载平衡的 IP 地址。


NOTE: 负载平衡器应使用与Astra控制中心工作节点IP地址位于同一子网中的IP地址。


NOTE: 如果要在 Tanzu Kubernetes 网格集群上托管 Astra 控制中心，请使用 `kubectl get nssxlbmonitors -a` 命令查看是否已将服务监控器配置为接受传入流量。如果存在一个，则不应安装 MetalLB ，因为现有服务监控器将覆盖任何新的负载平衡器配置。

有关详细信息，请参见 link:../get-started/install_acc.html#set-up-ingress-for-load-balancing["设置传入以进行负载平衡"^]。



== 网络要求

托管 Astra 控制中心的操作环境使用以下 TCP 端口进行通信。您应确保允许这些端口通过任何防火墙，并将防火墙配置为允许来自 Astra 网络的任何 HTTPS 传出流量。某些端口需要在托管 Astra 控制中心的环境与每个受管集群之间进行双向连接（请在适用时注明）。


NOTE: 您可以在双堆栈 Kubernetes 集群中部署 Astra 控制中心，而 Astra 控制中心则可以管理为双堆栈操作配置的应用程序和存储后端。有关双堆栈集群要求的详细信息，请参见 https://kubernetes.io/docs/concepts/services-networking/dual-stack/["Kubernetes 文档"^]。

|===
| 源 | 目标 | Port | 协议 | 目的 


| 客户端 PC | Astra 控制中心 | 443. | HTTPS | UI / API 访问 - 确保托管 Astra 控制中心的集群与每个受管集群之间的此端口是双向开放的 


| 指标使用者 | Astra 控制中心工作节点 | 9090 | HTTPS | 指标数据通信—确保每个受管集群都可以访问托管 Astra 控制中心的集群上的此端口 （需要双向通信） 


| Astra 控制中心 | 托管 Cloud Insights 服务 (https://www.netapp.com/cloud-services/cloud-insights/)[] | 443. | HTTPS | Cloud Insights 通信 


| Astra 控制中心 | Amazon S3 存储分段提供商 | 443. | HTTPS | Amazon S3 存储通信 


| Astra 控制中心 | NetApp AutoSupport (https://support.netapp.com)[] | 443. | HTTPS | NetApp AutoSupport 通信 
|===


== 支持的 Web 浏览器

Astra 控制中心支持最新版本的 Firefox ， Safari 和 Chrome ，最小分辨率为 1280 x 720 。



== 应用程序集群的其他要求

如果您计划使用以下Astra控制中心功能、请记住这些要求：

* *应用程序集群要求*： link:../get-started/setup_overview.html#prepare-your-environment-for-cluster-management-using-astra-control["集群管理要求"^]
+
** *受管应用程序要求*： link:../use/manage-apps.html#application-management-requirements["应用程序管理要求"^]
** *应用程序复制的其他要求*： link:../use/replicate_snapmirror.html#replication-prerequisites["复制前提条件"^]






== Google Anthos集群要求

在Google Anthos集群上托管Astra控制中心时、请注意、Google Anthos默认包括MetalLB负载平衡器和Istio入口网关服务、使您可以在安装期间轻松使用Astra控制中心的通用入口功能。请参见 link:install_acc.html#configure-astra-control-center["配置 Astra 控制中心"^] 了解详细信息。



== VMware Tanzu Kubernetes Grid 集群要求

在 VMware Tanzu Kubernetes Grid （ TKG ）或 Tanzu Kubernetes Grid Integrated Edition （ TKGi ）集群上托管 Astra Control Center 时，请记住以下注意事项。

* 在任何要由 Astra Control 管理的应用程序集群上禁用 TKG 或 TKGi 默认存储类强制实施。为此，您可以编辑命名空间集群上的 `TanuKubernetes Cluster` 资源。
* 在 TKG 或 TKGi 环境中部署 Astra 控制中心时，请注意 Astra Trident 的特定要求。有关详细信息，请参见 https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy.html#other-known-configuration-options["Astra Trident 文档"^]。



NOTE: 默认的 VMware TKG 和 TKGi 配置文件令牌将在部署后 10 小时过期。如果您使用的是 Tanzu 产品组合，则必须使用未过期的令牌生成 Tanzu Kubernetes 集群配置文件，以防止 Astra 控制中心与受管应用程序集群之间出现连接问题。有关说明，请访问 https://docs.vmware.com/en/VMware-NSX-T-Data-Center/3.2/nsx-application-platform/GUID-52A52C0B-9575-43B6-ADE2-E8640E22C29F.html["VMware NSX-T 数据中心产品文档。"^]



== 下一步行动

查看 link:quick-start.html["快速入门"^] 概述。
