---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: astra, control center, bugs, known issues, problems 
summary: 已知问题可确定可能妨碍您成功使用此版本产品的问题。 
---
= 已知问题
:hardbreaks:
:allow-uri-read: 
:source-highlighter: highlight.js
:icons: font
:imagesdir: ../media/release-notes/


[role="lead"]
已知问题可确定可能妨碍您成功使用此版本产品的问题。

以下已知问题会影响当前版本：

* <<如果在管理集群后添加了volumesnapshotclass、则应用程序备份和快照将失败>>
* <<使用设置的存储类部署应用程序后，应用程序克隆将失败>>
* <<如果kubeconfig"文件包含多个上下文、则使用Asta Control Center管理集群将失败>>
* <<在Isio环境中、监控POD可能会崩溃>>
* <<当 Astra Trident 脱机时，应用程序数据管理操作失败，并显示内部服务错误（ 500 ）>>




== 如果在管理集群后添加了volumesnapshotclass、则应用程序备份和快照将失败

在这种情况下、备份和快照失败、并显示`UI 500错误`。作为临时解决策 、刷新应用程序列表。



== 使用设置的存储类部署应用程序后，应用程序克隆将失败

在使用显式设置的存储类（例如， `helm install ...-set global.storageClass=netapp-cvs-perf-至 至至` ）部署应用程序后，后续克隆应用程序的尝试要求目标集群具有最初指定的存储类。将具有显式设置的存储类的应用程序克隆到没有相同存储类的集群将失败。此情况下没有恢复步骤。



== 如果kubeconfig"文件包含多个上下文、则使用Asta Control Center管理集群将失败

不能将 kubeconfig 与多个集群和上下文结合使用。请参见 link:https://kb.netapp.com/Cloud/Astra/Control/Managing_cluster_with_Astra_Control_Center_may_fail_when_using_default_kubeconfig_file_contains_more_than_one_context["知识库文章"^] 有关详细信息 ...



== 在Isio环境中、监控POD可能会崩溃

如果在Istio环境中将Astra控制中心与Cloud Insights 配对、则 `telegraf-rs` POD可能会崩溃。作为临时解决策，请执行以下步骤：

. 找到崩溃的POD：
+
[listing]
----
kubectl -n netapp-monitoring get pod | grep Error
----
+
您应看到类似于以下内容的输出：

+
[listing]
----
NAME READY STATUS RESTARTS AGE
telegraf-rs-fhhrh 1/2 Error 2 (26s ago) 32s
----
. 重新启动崩溃的Pod、更换 `<pod_name_from_output>` 使用受影响POD的名称：
+
[listing]
----
kubectl -n netapp-monitoring delete pod <pod_name_from_output>
----
+
您应看到类似于以下内容的输出：

+
[listing]
----
pod "telegraf-rs-fhhrh" deleted
----
. 确认POD已重新启动且未处于错误状态：
+
[listing]
----
kubectl -n netapp-monitoring get pod
----
+
您应看到类似于以下内容的输出：

+
[listing]
----
NAME READY STATUS RESTARTS AGE
telegraf-rs-rrnsb 2/2 Running 0 11s
----




== 当 Astra Trident 脱机时，应用程序数据管理操作失败，并显示内部服务错误（ 500 ）

如果应用程序集群上的 Astra Trident 脱机（并恢复联机），并且在尝试应用程序数据管理时遇到 500 个内部服务错误，请重新启动应用程序集群中的所有 Kubernetes 节点以还原功能。



== 了解更多信息

* link:../release-notes/known-limitations.html["已知限制"]

