---
sidebar: sidebar 
permalink: release-notes/resolved-issues.html 
keywords: astra, control center, fixed bugs, fixes, resolved issues 
summary: 已知问题可确定可能妨碍您成功使用此版本产品的问题。 
---
= 已解决的问题
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/release-notes/


此版本的产品已更正这些问题。



== 额外的备份会作为计划备份的一部分保留

有时， Astra 控制中心中的一个或多个备份会保留到超出备份计划中指定保留的数量的位置。这些额外备份应作为计划备份的一部分删除，但不会删除，并且会停留在 `pending` 状态。



== 在 Astra 控制中心中，使用具有小数单位的 PVC 的应用程序的备份或克隆失败

使用十进制单位创建的卷将使用 Astra 控制中心备份或克隆过程失败。



== Astra 控制中心 UI 显示应用程序资源更改（如永久性卷更改）的速度较慢

在执行数据保护操作（克隆，备份，还原）并随后调整永久性卷大小后，在 UI 中显示新卷大小之前，最长会有 20 分钟的延迟。添加或修改任何应用程序资源时， UI 也会出现此延迟。在这种情况下，数据保护操作将在几分钟内成功完成，您可以使用存储后端的管理软件确认卷大小的更改。



== 安装期间， Astra 控制中心自定义资源定义创建的集群角色绑定不正确

此版本不再需要修补程序来更正安装期间的集群角色绑定。



== ASUP 收集停留在 " 正在生成 " 或 " 正在上传 " 状态

如果停止或重新启动 ASUP POD ， ASUP 收集可能会停留在 " 正在生成 " 或 " 正在上传 " 状态。



== 操作员部署的应用程序和命名空间

操作员及其部署的应用程序必须使用同一命名空间。Astra Control 仅支持每个命名空间使用一个操作员部署的应用程序。



== 了解更多信息

* link:../release-notes/known-issues.html["已知问题"]
* link:../release-notes/known-limitations.html["已知限制"]
* link:../release-notes/known-issues-ads.html["有关 Astra Data Store 预览版和此 Astra 控制中心版本的已知问题"]

